/** A single negative test case in the alternate flow */
export interface NegativeCase {
  Type: string;
  Scenario: string;
  ExpectedResult: string;
}

/** Positive (happy path) flow */
export interface PositiveFlow {
  Description: string;
  AcceptanceCriteria: string[];
}

/** Alternate (failure) flow */
export interface AlternateFlow {
  Description: string;
  NegativeCases: NegativeCase[];
}

/** Structured Test Card generated by the backend */
export interface TestCard {
  TestCardID: string;
  SourceUserStory: string;
  DomainActor: string;
  CoreAction: string;
  TargetObject: string;
  UnitUnderTest: string;
  SCMDomainRuleID: string;
  Preconditions: string[];
  PositiveFlow: PositiveFlow;
  AlternateFlow: AlternateFlow;
}

/** Validation result returned alongside a test card */
export interface TestCardValidation {
  is_valid: boolean;
  completeness_score: number;
  errors: string[];
  warnings: string[];
}

/** Response from POST /api/process-user-story */
export interface ProcessUserStoryResponse {
  success: boolean;
  test_card: TestCard;
  validation: TestCardValidation;
  execution_id: number;
}

/** Response from POST /api/extract-story-elements */
export interface StoryElements {
  success: boolean;
  elements: {
    actor: string;
    action: string;
    benefit: string;
    has_acceptance_criteria: boolean;
  };
}
